<a href="https://colab.research.google.com/github/mthimkulu23/Standard-Bank-Tech-Impact-Challenge-Xente-Credit-Scoring-Challenge/blob/main/Standard_Bank_Tech_Impact_Challenge_Xente_Credit_Scoring_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import pandas as pd

#  Load data
Train = pd.read_csv('Train.csv')
Train

# check_duplicates = Train.duplicated().sum()
# check_duplicates


# Train.isnull().sum()

,CustomerId,TransactionStartTime,Value,Amount,TransactionId,BatchId,SubscriptionId,CurrencyCode,CountryCode,ProviderId,...,LoanId,PaidOnDate,IsFinalPayBack,InvestorId,DueDate,LoanApplicationId,PayBackId,ThirdPartyId,IsThirdPartyConfirmed,IsDefaulted
0,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CustomerId_27,2018-09-25 09:20:29,550.0,-550.0,TransactionId_2235,BatchId_820,SubscriptionId_2,UGX,256,ProviderId_1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CustomerId_27,2018-09-25 10:33:31,550.0,-550.0,TransactionId_1053,BatchId_210,SubscriptionId_4,UGX,256,ProviderId_1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CustomerId_27,2018-09-27 10:26:41,1000.0,-1000.0,TransactionId_2633,BatchId_876,SubscriptionId_4,UGX,256,ProviderId_1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CustomerId_27,2018-09-27 12:44:21,500.0,-500.0,TransactionId_71,BatchId_1362,SubscriptionId_4,UGX,256,ProviderId_1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2095,CustomerId_28,2019-03-30 21:55:11,2000.0,-2000.0,TransactionId_1185,BatchId_2069,SubscriptionId_7,UGX,256,ProviderId_1,...,LoanId_293,2019-04-29 14:35:17,1.0,InvestorId_1,2019-04-29 21:55:06,LoanApplicationId_524,PayBackId_1106,ThirdPartyId_857,1.0,0.0
2096,CustomerId_28,2019-03-30 23:54:07,5000.0,-5000.0,TransactionId_1824,BatchId_1552,SubscriptionId_7,UGX,256,ProviderId_1,...,LoanId_1040,2019-04-29 14:32:37,1.0,InvestorId_1,2019-04-29 23:53:57,LoanApplicationId_1441,PayBackId_966,ThirdPartyId_958,1.0,0.0
2097,CustomerId_34,2019-03-31 05:40:10,5000.0,-5000.0,TransactionId_2507,BatchId_1093,SubscriptionId_7,UGX,256,ProviderId_1,...,LoanId_1585,2019-06-15 06:20:05,1.0,InvestorId_1,2019-04-30 05:40:02,LoanApplicationId_1466,PayBackId_1271,ThirdPartyId_1981,1.0,0.0
2098,CustomerId_346,2019-03-31 09:37:19,1500.0,-1500.0,TransactionId_540,BatchId_1239,SubscriptionId_7,UGX,256,ProviderId_1,...,LoanId_1314,2019-04-23 15:44:15,1.0,InvestorId_1,2019-04-30 09:37:15,LoanApplicationId_1389,PayBackId_945,ThirdPartyId_705,1.0,0.0
2099,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,LoanId_1570,2019-04-10 17:33:19,1.0,InvestorId_1,2019-04-30 12:16:26,LoanApplicationId_57,PayBackId_830,ThirdPartyId_899,1.0,0.0

In [65]:
#  Load data
test = pd.read_csv('Test.csv')
test

# check_duplicates = test.duplicated().sum()
# check_duplicates

# test.isnull().sum()

,CustomerId,TransactionStartTime,Value,Amount,TransactionId,BatchId,SubscriptionId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,TransactionStatus,IssuedDateLoan,LoanId,InvestorId,LoanApplicationId,ThirdPartyId
0,CustomerId_310,2019-03-31 13:33:05,14000.0,-14000.0,TransactionId_925,BatchId_1144,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_7,airtime,ChannelId_1,1,2019-03-31 13:33:04,LoanId_1027,InvestorId_1,LoanApplicationId_825,ThirdPartyId_1175
1,CustomerId_243,2019-03-31 15:04:09,1000.0,-1000.0,TransactionId_1080,BatchId_1214,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_8,data_bundles,ChannelId_1,1,2019-03-31 15:04:08,LoanId_768,InvestorId_1,LoanApplicationId_68,ThirdPartyId_604
2,CustomerId_142,2019-03-31 17:31:11,2500.0,-2500.0,TransactionId_2315,BatchId_2150,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_7,airtime,ChannelId_1,1,2019-03-31 17:31:09,LoanId_1067,InvestorId_1,LoanApplicationId_1223,ThirdPartyId_1521
3,CustomerId_142,2019-03-31 17:32:15,500.0,-500.0,TransactionId_1466,BatchId_1071,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_7,airtime,ChannelId_1,1,2019-03-31 17:32:14,LoanId_202,InvestorId_1,LoanApplicationId_633,ThirdPartyId_406
4,CustomerId_142,2019-03-31 17:34:41,1000.0,-1000.0,TransactionId_337,BatchId_2477,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_7,airtime,ChannelId_1,1,2019-03-31 17:34:40,LoanId_533,InvestorId_1,LoanApplicationId_309,ThirdPartyId_302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,CustomerId_412,2019-07-16 00:18:46,500.0,-500.0,TransactionId_680,BatchId_2079,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_1,airtime,ChannelId_1,0,NaN,NaN,NaN,NaN,NaN
901,CustomerId_326,2019-07-16 03:17:01,1000.0,-1000.0,TransactionId_2504,BatchId_1432,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_7,airtime,ChannelId_1,0,NaN,NaN,NaN,NaN,NaN
902,CustomerId_497,2019-07-16 15:06:22,1000.0,-1000.0,TransactionId_995,BatchId_1410,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_7,airtime,ChannelId_1,0,NaN,NaN,NaN,NaN,NaN
903,CustomerId_497,2019-07-16 15:09:58,800.0,-800.0,TransactionId_708,BatchId_1343,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_3,airtime,ChannelId_1,0,NaN,NaN,NaN,NaN,NaN
904,CustomerId_372,2019-07-17 05:34:45,1900.0,-1900.0,TransactionId_585,BatchId_665,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_7,airtime,ChannelId_1,0,NaN,NaN,NaN,NaN,NaN

In [66]:
#  Load data
unlinked_masked = pd.read_csv('unlinked_masked_final.csv')
unlinked_masked

# check_duplicates = unlinked_masked.duplicated().sum()
# check_duplicates

# unlinked_masked.isnull().sum()

,TransactionId,BatchId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime
0,TransactionId_18876,BatchId_7899,CustomerId_250,UGX,256,ProviderId_2,ProductId_8,data_bundles,ChannelId_3,2000.0,2000.0,30/6/19 22:57:49
1,TransactionId_15089,BatchId_8829,CustomerId_423,UGX,256,ProviderId_5,ProductId_7,airtime,ChannelId_3,800.0,800.0,30/6/19 22:39:11
2,TransactionId_9561,BatchId_15250,CustomerId_423,UGX,256,ProviderId_2,ProductId_10,financial_services,ChannelId_3,2000.0,2000.0,30/6/19 22:35:53
3,TransactionId_3635,BatchId_14442,CustomerId_316,UGX,256,ProviderId_4,ProductId_3,airtime,ChannelId_3,1000.0,1000.0,30/6/19 19:47:00
4,TransactionId_3104,BatchId_5171,CustomerId_193,UGX,256,ProviderId_5,ProductId_1,airtime,ChannelId_3,5000.0,5000.0,30/6/19 19:11:01
...,...,...,...,...,...,...,...,...,...,...,...,...
16322,TransactionId_11472,BatchId_12998,CustomerId_282,UGX,256,ProviderId_5,ProductId_3,airtime,ChannelId_3,1000.0,1000.0,1/1/19 6:28:43
16323,TransactionId_18689,BatchId_10292,CustomerId_282,UGX,256,ProviderId_5,ProductId_8,data_bundles,ChannelId_3,2000.0,2000.0,1/1/19 5:10:25
16324,TransactionId_17879,BatchId_16972,CustomerId_282,UGX,256,ProviderId_5,ProductId_3,airtime,ChannelId_3,2000.0,2000.0,1/1/19 4:54:08
16325,TransactionId_6532,BatchId_11541,CustomerId_180,UGX,256,ProviderId_3,ProductId_3,airtime,ChannelId_3,2000.0,2000.0,1/1/19 0:46:25
16326,TransactionId_16784,BatchId_11840,CustomerId_310,UGX,256,ProviderId_5,ProductId_7,airtime,ChannelId_3,2000.0,2000.0,1/1/19 0:12:01

In [67]:
#merging dataset for train
merge_train = Train.merge(unlinked_masked, how="inner", on = "CustomerId")
merge_train

,CustomerId,TransactionStartTime_x,Value_x,Amount_x,TransactionId_x,BatchId_x,SubscriptionId,CurrencyCode_x,CountryCode_x,ProviderId_x,...,BatchId_y,CurrencyCode_y,CountryCode_y,ProviderId_y,ProductId_y,ProductCategory_y,ChannelId_y,Amount_y,Value_y,TransactionStartTime_y
0,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,BatchId_12971,UGX,256,ProviderId_5,ProductId_8,data_bundles,ChannelId_3,500.0,500.0,30/6/19 13:10:31
1,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,BatchId_7669,UGX,256,ProviderId_5,ProductId_7,airtime,ChannelId_3,500.0,500.0,29/6/19 7:22:54
2,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,BatchId_18228,UGX,256,ProviderId_5,ProductId_3,airtime,ChannelId_3,1000.0,1000.0,28/6/19 16:47:28
3,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,BatchId_14282,UGX,256,ProviderId_5,ProductId_8,data_bundles,ChannelId_3,500.0,500.0,28/6/19 14:23:39
4,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,BatchId_5595,UGX,256,ProviderId_3,ProductId_9,utility_bill,ChannelId_3,50000.0,53500.0,28/6/19 13:32:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130055,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_8350,UGX,256,ProviderId_2,ProductId_10,financial_services,ChannelId_3,5000.0,5000.0,23/1/19 18:27:59
130056,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_17898,UGX,256,ProviderId_5,ProductId_1,airtime,ChannelId_3,2000.0,2000.0,22/1/19 5:01:07
130057,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_7844,UGX,256,ProviderId_5,ProductId_1,airtime,ChannelId_3,1000.0,1000.0,21/1/19 5:08:49
130058,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_10254,UGX,256,ProviderId_5,ProductId_3,airtime,ChannelId_3,1000.0,1000.0,21/1/19 4:07:40
130059,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_17114,UGX,256,ProviderId_2,ProductId_10,financial_services,ChannelId_3,3000.0,3000.0,19/1/19 9:32:57

In [68]:
#merging dataset for test
merge_test = test.merge(unlinked_masked, how="inner", on = "CustomerId")
merge_test

,CustomerId,TransactionStartTime_x,Value_x,Amount_x,TransactionId_x,BatchId_x,SubscriptionId,CurrencyCode_x,CountryCode_x,ProviderId_x,...,BatchId_y,CurrencyCode_y,CountryCode_y,ProviderId_y,ProductId_y,ProductCategory_y,ChannelId_y,Amount_y,Value_y,TransactionStartTime_y
0,CustomerId_310,2019-03-31 13:33:05,14000.0,-14000.0,TransactionId_925,BatchId_1144,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_16936,UGX,256,ProviderId_5,ProductId_1,airtime,ChannelId_3,1000.0,1000.0,3/5/19 17:26:30
1,CustomerId_310,2019-03-31 13:33:05,14000.0,-14000.0,TransactionId_925,BatchId_1144,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_17100,UGX,256,ProviderId_5,ProductId_1,airtime,ChannelId_3,1000.0,1000.0,3/5/19 11:49:56
2,CustomerId_310,2019-03-31 13:33:05,14000.0,-14000.0,TransactionId_925,BatchId_1144,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_11594,UGX,256,ProviderId_5,ProductId_7,airtime,ChannelId_3,1000.0,1000.0,3/5/19 11:26:08
3,CustomerId_310,2019-03-31 13:33:05,14000.0,-14000.0,TransactionId_925,BatchId_1144,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_7110,UGX,256,ProviderId_5,ProductId_2,data_bundles,ChannelId_3,1750.0,1750.0,1/5/19 8:33:27
4,CustomerId_310,2019-03-31 13:33:05,14000.0,-14000.0,TransactionId_925,BatchId_1144,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_18849,UGX,256,ProviderId_5,ProductId_2,data_bundles,ChannelId_3,1750.0,1750.0,1/5/19 7:30:47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73508,CustomerId_326,2019-07-16 03:17:01,1000.0,-1000.0,TransactionId_2504,BatchId_1432,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_14421,UGX,256,ProviderId_4,ProductId_10,financial_services,ChannelId_3,9000.0,9000.0,15/1/19 5:34:26
73509,CustomerId_326,2019-07-16 03:17:01,1000.0,-1000.0,TransactionId_2504,BatchId_1432,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_12702,UGX,256,ProviderId_5,ProductId_7,airtime,ChannelId_3,10000.0,10000.0,4/1/19 10:12:03
73510,CustomerId_326,2019-07-16 03:17:01,1000.0,-1000.0,TransactionId_2504,BatchId_1432,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_15242,UGX,256,ProviderId_4,ProductId_10,financial_services,ChannelId_3,20000.0,20000.0,4/1/19 9:59:06
73511,CustomerId_326,2019-07-16 03:17:01,1000.0,-1000.0,TransactionId_2504,BatchId_1432,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_17563,UGX,256,ProviderId_5,ProductId_3,airtime,ChannelId_3,3000.0,3000.0,4/1/19 1:53:24
73512,CustomerId_326,2019-07-16 03:17:01,1000.0,-1000.0,TransactionId_2504,BatchId_1432,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_15580,UGX,256,ProviderId_4,ProductId_10,financial_services,ChannelId_3,1600.0,1600.0,4/1/19 1:51:42

In [83]:
variable_definition = pd.read_csv('VariableDefinitions.csv')
variable_definition

                 Variable                                         Definition
0              CustomerId  Unique number identifying the customer on plat...
1    TransactionStartTime                             Transaction start time
2                   Value                               Value of transaction
3                  Amount                  Value of Transaction with charges
4           TransactionId          Unique transaction identifier on platform
5                 BatchId  Identifier for bulk transactions being done on...
6          SubscriptionId  You can have one account with multiple subscri...
7            CurrencyCode                                   Country currency
8             CountryCode             Numerical geographical code of country
9              ProviderId                     Source provider of Item bought
10              ProductId                             Item name being bought
11        ProductCategory                                    Type of product
12              ChannelId  Identifies if customer used Xente Paylater on ...
13      TransactionStatus  Loan application status (1=accepted, 0 = rejec...
14         IssuedDateLoan                                Date loan is issued
15             AmountLoan                           Value of the loan issued
16               Currency                    Ugandan shillings Denominations
17                 LoanId                 Loan transaction unique identifier
18             PaidOnDate                    Date on which the loan was paid
19         IsFinalPayBack                           Last payback installment
20             InvestorId                       Loan issuer or network owner
21                DueDate                                   Date loan is due
22      LoanApplicationId             unique identifier for loan application
23              PayBackId                     Loan payback number identifier
24           ThirdPartyId                  Transaction id for a loan payback
25  IsThirdPartyConfirmed                   loan order succeeded on platform
26            IsDefaulted  Exceeded agreed payback time (1 = default, 0 =...

In [69]:
check_duplicates = merge_train.isnull().sum()
check_duplicates

CustomerId                    0
TransactionStartTime_x        0
Value_x                       0
Amount_x                      0
TransactionId_x               0
BatchId_x                     0
SubscriptionId                0
CurrencyCode_x                0
CountryCode_x                 0
ProviderId_x                  0
ProductId_x                   0
ProductCategory_x             0
ChannelId_x                   0
TransactionStatus             0
IssuedDateLoan            11736
AmountLoan                11736
Currency                  11736
LoanId                    11736
PaidOnDate                11736
IsFinalPayBack            11736
InvestorId                11736
DueDate                   11925
LoanApplicationId         12125
PayBackId                 11736
ThirdPartyId              11736
IsThirdPartyConfirmed     11736
IsDefaulted               11736
TransactionId_y               0
BatchId_y                     0
CurrencyCode_y                0
CountryCode_y                 0
ProviderId_y                  0
ProductId_y                   0
ProductCategory_y             0
ChannelId_y                   0
Amount_y                      0
Value_y                       0
TransactionStartTime_y        0
dtype: int64

In [77]:

fill_nulls_train = merge_train.fillna("Unknown")
fill_nulls_train

# check_duplicates = fill_nulls_train.isnull().sum()
# check_duplicates

CustomerId                0
TransactionStartTime_x    0
Value_x                   0
Amount_x                  0
TransactionId_x           0
BatchId_x                 0
SubscriptionId            0
CurrencyCode_x            0
CountryCode_x             0
ProviderId_x              0
ProductId_x               0
ProductCategory_x         0
ChannelId_x               0
TransactionStatus         0
IssuedDateLoan            0
AmountLoan                0
Currency                  0
LoanId                    0
PaidOnDate                0
IsFinalPayBack            0
InvestorId                0
DueDate                   0
LoanApplicationId         0
PayBackId                 0
ThirdPartyId              0
IsThirdPartyConfirmed     0
IsDefaulted               0
TransactionId_y           0
BatchId_y                 0
CurrencyCode_y            0
CountryCode_y             0
ProviderId_y              0
ProductId_y               0
ProductCategory_y         0
ChannelId_y               0
Amount_y                  0
Value_y                   0
TransactionStartTime_y    0
dtype: int64

In [71]:
check_duplicates = merge_test.isnull().sum()
check_duplicates


fill_null_test = merge_test.fillna("Unknown")
fill_null_test


check_dupli = fill_null_test.isnull().sum()
check_dupli

CustomerId                0
TransactionStartTime_x    0
Value_x                   0
Amount_x                  0
TransactionId_x           0
BatchId_x                 0
SubscriptionId            0
CurrencyCode_x            0
CountryCode_x             0
ProviderId_x              0
ProductId_x               0
ProductCategory_x         0
ChannelId_x               0
TransactionStatus         0
IssuedDateLoan            0
LoanId                    0
InvestorId                0
LoanApplicationId         0
ThirdPartyId              0
TransactionId_y           0
BatchId_y                 0
CurrencyCode_y            0
CountryCode_y             0
ProviderId_y              0
ProductId_y               0
ProductCategory_y         0
ChannelId_y               0
Amount_y                  0
Value_y                   0
TransactionStartTime_y    0
dtype: int64

In [78]:
drop_target = fill_nulls_train.drop('IsDefaulted', axis=1)
drop_target

,CustomerId,TransactionStartTime_x,Value_x,Amount_x,TransactionId_x,BatchId_x,SubscriptionId,CurrencyCode_x,CountryCode_x,ProviderId_x,...,BatchId_y,CurrencyCode_y,CountryCode_y,ProviderId_y,ProductId_y,ProductCategory_y,ChannelId_y,Amount_y,Value_y,TransactionStartTime_y
0,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,BatchId_12971,UGX,256,ProviderId_5,ProductId_8,data_bundles,ChannelId_3,500.0,500.0,30/6/19 13:10:31
1,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,BatchId_7669,UGX,256,ProviderId_5,ProductId_7,airtime,ChannelId_3,500.0,500.0,29/6/19 7:22:54
2,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,BatchId_18228,UGX,256,ProviderId_5,ProductId_3,airtime,ChannelId_3,1000.0,1000.0,28/6/19 16:47:28
3,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,BatchId_14282,UGX,256,ProviderId_5,ProductId_8,data_bundles,ChannelId_3,500.0,500.0,28/6/19 14:23:39
4,CustomerId_27,2018-09-21 12:17:39,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,...,BatchId_5595,UGX,256,ProviderId_3,ProductId_9,utility_bill,ChannelId_3,50000.0,53500.0,28/6/19 13:32:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130055,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_8350,UGX,256,ProviderId_2,ProductId_10,financial_services,ChannelId_3,5000.0,5000.0,23/1/19 18:27:59
130056,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_17898,UGX,256,ProviderId_5,ProductId_1,airtime,ChannelId_3,2000.0,2000.0,22/1/19 5:01:07
130057,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_7844,UGX,256,ProviderId_5,ProductId_1,airtime,ChannelId_3,1000.0,1000.0,21/1/19 5:08:49
130058,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_10254,UGX,256,ProviderId_5,ProductId_3,airtime,ChannelId_3,1000.0,1000.0,21/1/19 4:07:40
130059,CustomerId_188,2019-03-31 12:16:33,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,...,BatchId_17114,UGX,256,ProviderId_2,ProductId_10,financial_services,ChannelId_3,3000.0,3000.0,19/1/19 9:32:57

In [80]:
y = fill_nulls_train['IsDefaulted']
y

0         Unknown
1         Unknown
2         Unknown
3         Unknown
4         Unknown
           ...
130055        0.0
130056        0.0
130057        0.0
130058        0.0
130059        0.0
Name: IsDefaulted, Length: 130060, dtype: object

In [88]:
x = drop_target.drop(["TransactionStartTime_y","TransactionStartTime_x", "CustomerId", "PaidOnDate", "DueDate"],axis = 1)
x

,Value_x,Amount_x,TransactionId_x,BatchId_x,SubscriptionId,CurrencyCode_x,CountryCode_x,ProviderId_x,ProductId_x,ProductCategory_x,...,TransactionId_y,BatchId_y,CurrencyCode_y,CountryCode_y,ProviderId_y,ProductId_y,ProductCategory_y,ChannelId_y,Amount_y,Value_y
0,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,ProductId_7,airtime,...,TransactionId_7202,BatchId_12971,UGX,256,ProviderId_5,ProductId_8,data_bundles,ChannelId_3,500.0,500.0
1,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,ProductId_7,airtime,...,TransactionId_8387,BatchId_7669,UGX,256,ProviderId_5,ProductId_7,airtime,ChannelId_3,500.0,500.0
2,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,ProductId_7,airtime,...,TransactionId_8415,BatchId_18228,UGX,256,ProviderId_5,ProductId_3,airtime,ChannelId_3,1000.0,1000.0
3,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,ProductId_7,airtime,...,TransactionId_9947,BatchId_14282,UGX,256,ProviderId_5,ProductId_8,data_bundles,ChannelId_3,500.0,500.0
4,550.0,-550.0,TransactionId_1683,BatchId_641,SubscriptionId_2,UGX,256,ProviderId_1,ProductId_7,airtime,...,TransactionId_10271,BatchId_5595,UGX,256,ProviderId_3,ProductId_9,utility_bill,ChannelId_3,50000.0,53500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130055,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_3,airtime,...,TransactionId_15722,BatchId_8350,UGX,256,ProviderId_2,ProductId_10,financial_services,ChannelId_3,5000.0,5000.0
130056,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_3,airtime,...,TransactionId_8814,BatchId_17898,UGX,256,ProviderId_5,ProductId_1,airtime,ChannelId_3,2000.0,2000.0
130057,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_3,airtime,...,TransactionId_14667,BatchId_7844,UGX,256,ProviderId_5,ProductId_1,airtime,ChannelId_3,1000.0,1000.0
130058,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_3,airtime,...,TransactionId_3054,BatchId_10254,UGX,256,ProviderId_5,ProductId_3,airtime,ChannelId_3,1000.0,1000.0
130059,1000.0,-1000.0,TransactionId_1889,BatchId_355,SubscriptionId_7,UGX,256,ProviderId_1,ProductId_3,airtime,...,TransactionId_16133,BatchId_17114,UGX,256,ProviderId_2,ProductId_10,financial_services,ChannelId_3,3000.0,3000.0